FROM debian:bookworm

ENV LFS=/mnt/lfs

WORKDIR /opt/lfs

ADD version-check.sh version-check.sh

RUN bash version-check.sh

RUN apt-get update && apt-get upgrade && apt install --no-install-recommends -y \
    ca-certificates  \    
    vim \
    binutils \
    bison \
    gawk \
    gcc \
    g++ \
    m4 \
    make \
    patch \
    python3 \
    texinfo \
    xz-utils \
    wget \
  && rm -rf /var/lib/apt/lists/* \
  && apt autoclean && apt autoremove 

RUN ln -sf /usr/bin/bash /usr/bin/sh && \
  #seems to be the same file now?
  # ln -sf /usr/bin/awk /usr/bin/gawk && \
  ln -sf /usr/bin/yacc /usr/bin/bison
