FROM lfs/base:latest

# TODO - process all this into an automated fashion

alias ll="ls -lart"
cd $LFS



# pulling all sources to build/configure/compile
mkdir -pv $LFS/sources
chmod -v a+wt $LFS/sources

# add config/ files

pushd $LFS/sources
wget --input-file=wget-list-sysv --continue --directory-prefix=$LFS/sources
md5sum -c md5sums
popd
chown root:root $LFS/sources/*





# minimal LFS FS setup
mkdir -pv $LFS/{etc,var} $LFS/usr/{bin,lib,sbin}

for i in bin lib sbin; do
  ln -sv usr/$i $LFS/$i
done

case $(uname -m) in
  x86_64) mkdir -pv $LFS/lib64 ;;
esac
mkdir -pv $LFS/tools




# lfs user setup
groupadd lfs
useradd -s /bin/bash -g lfs -m -k /dev/null lfs
# passwd lfs # if you want to be able to login to the user not from root
chown -v lfs $LFS/{usr{,/*},lib,var,etc,bin,sbin,tools}
case $(uname -m) in
  x86_64) chown -v lfs $LFS/lib64 ;;
esac
su - lfs
cat > ~/.bash_profile << "EOF"
exec env -i HOME=$HOME TERM=$TERM PS1='\u:\w\$ ' /bin/bash
EOF

cat > ~/.bashrc << "EOF"
set +h
umask 022
LFS=/mnt/lfs
LC_ALL=POSIX
LFS_TGT=$(uname -m)-lfs-linux-gnu
PATH=/usr/bin
if [ ! -L /bin ]; then PATH=/bin:$PATH; fi
PATH=$LFS/tools/bin:$PATH
CONFIG_SITE=$LFS/usr/share/config.site
export LFS LC_ALL LFS_TGT PATH CONFIG_SITE
EOF

cat >> ~/.bashrc << "EOF"
export MAKEFLAGS=-j$(nproc)
EOF
source ~/.bash_profile



# checks before continuing
LFS is set and = /mnt/lfs
sh -> bash
awk -> gawk
yacc -> bison
33  which sh
34  ls -la /usr/bin/sh
35  which gawk
36  ls -la /usr/bin/gawk
37  ls -la /usr/bin/awk
38  which awk
39  awk -V
40  gawk -V
41  which awk
42  which gawk
43  ls -la /usr/bin/awk
44  ls -la /etc/alternatives/awk
45  which yacc
46  ls -la /usr/bin/yacc
47  ls -la /etc/alternatives/yacc
48  cat /usr/bin/bison.yacc



# compiling
cd $LFS/sources
tar -xvf binutils-2.43.1.tar.xz
cd binutils-2.43.1
mkdir -v build
cd build
../configure --prefix=$LFS/tools \
             --with-sysroot=$LFS \
             --target=$LFS_TGT   \
             --disable-nls       \
             --enable-gprofng=no \
             --disable-werror    \
             --enable-new-dtags  \
             --enable-default-hash-style=gnu
make
make install
cd $LFS/sources
rm -rf binutils-2.43.1


cd $LFS/sources
tar -xvf gcc-14.2.0.tar.xz
cd gcc-14.2.0
tar -xvf ../mpfr-4.2.1.tar.xz
mv -v mpfr-4.2.1 mpfr
tar -xvf ../gmp-6.3.0.tar.xz
mv -v gmp-6.3.0 gmp
tar -xvf ../mpc-1.3.1.tar.gz
mv -v mpc-1.3.1 mpc
case $(uname -m) in
  x86_64)
    sed -e '/m64=/s/lib64/lib/' \
        -i.orig gcc/config/i386/t-linux64
 ;;
esac
mkdir -v build
cd       build
../configure                  \
    --target=$LFS_TGT         \
    --prefix=$LFS/tools       \
    --with-glibc-version=2.40 \
    --with-sysroot=$LFS       \
    --with-newlib             \
    --without-headers         \
    --enable-default-pie      \
    --enable-default-ssp      \
    --disable-nls             \
    --disable-shared          \
    --disable-multilib        \
    --disable-threads         \
    --disable-libatomic       \
    --disable-libgomp         \
    --disable-libquadmath     \
    --disable-libssp          \
    --disable-libvtv          \
    --disable-libstdcxx       \
    --enable-languages=c,c++
make

# TODO - issue here below, believe it's missing a library that it either needs to exist in the image or linked
# checking for suffix of object files... configure: error: in `/mnt/lfs/sources/gcc-14.2.0/build/x86_64-lfs-linux-gnu/libgcc':
#   configure: error: cannot compute suffix of object files: cannot compile
#   See `config.log' for more details

make install 
cd ..
cat gcc/limitx.h gcc/glimits.h gcc/limity.h > `dirname $($LFS_TGT-gcc -print-libgcc-file-name)`/include/limits.h
cd $LFS/sources
rm -rf gcc-14.2.0





cd $LFS/sources
tar -xvf linux-6.10.5.tar.xz
cd linux-6.10.5
make mrproper
make headers
find usr/include -type f ! -name '*.h' -delete
cp -rv usr/include $LFS/usr
cd $LFS/sources
rm -rf linux-6.10.5

cd $LFS/sources
tar -xvf 
cd 
case $(uname -m) in
    i?86)   ln -sfv ld-linux.so.2 $LFS/lib/ld-lsb.so.3
    ;;
    x86_64) ln -sfv ../lib/ld-linux-x86-64.so.2 $LFS/lib64
            ln -sfv ../lib/ld-linux-x86-64.so.2 $LFS/lib64/ld-lsb-x86-64.so.3
    ;;
esac
patch -Np1 -i ../glibc-2.40-fhs-1.patch
mkdir -v build
cd       build
echo "rootsbindir=/usr/sbin" > configparms
../configure                             \
      --prefix=/usr                      \
      --host=$LFS_TGT                    \
      --build=$(../scripts/config.guess) \
      --enable-kernel=4.19               \
      --with-headers=$LFS/usr/include    \
      --disable-nscd                     \
      libc_cv_slibdir=/usr/lib
make
make DESTDIR=$LFS install
sed '/RTLDLIST=/s@/usr@@g' -i $LFS/usr/bin/ldd




# sanity check the bare toolchain before continuing
echo 'int main(){}' | $LFS_TGT-gcc -xc -
readelf -l a.out | grep ld-linux
# assert
rm -v a.out

